### ISSUE TITLE
pls support folia

### ISSUE THREAD

**Issue by xiaoluofa** [Sideways-Sky/Tool-Trims#1]

**Comment by Mellurboo** [comment]
Folia even says on its home page "will break most public plugins". **if you aren't running a server with a player count in the hundreds don't use folia YET** its still new and plugin developers haven't had time to adapt to it

https://cdn.discordapp.com/attachments/1129945986698059867/1223243949779583006/image.png?ex=661925b4&is=6606b0b4&hm=561369f2e9b05d040b9a45b331beaae54b8d207462659193ec74abff62c2e9d8&

**Comment by 404forever1** [comment]
> Folia even says on its home page "will break most public plugins". **if you aren't running a server with a player count in the hundreds don't use folia YET** its still new and plugin developers haven't had time to adapt to it
> 
> https://cdn.discordapp.com/attachments/1129945986698059867/1223243949779583006/image.png?ex=661925b4&is=6606b0b4&hm=561369f2e9b05d040b9a45b331beaae54b8d207462659193ec74abff62c2e9d8&

My server has 200 players online at the same time, running on folia. I hope you can support folia. Thank you very much!
