### ISSUE TITLE
mod imcompatibility

### ISSUE THREAD

**Issue by VaporeonScripts** [Sideways-Sky/Tool-Trims#2]
the latest neoforge 1.21.1 version of this mod: https://modrinth.com/datapack/tool-trims/version/2.2.1+mod
causes the item in crafting table to disappear
![image](https://github.com/user-attachments/assets/872db443-d37d-4e72-b312-e27a17c7d2c1)

**Comment by VaporeonScripts** [comment]
removing "fast workbench" mod also fixes the problem, but the issue comes from there

**Comment by AnsonEyre** [comment]
This seems to be an issue with the OG ToolTrims. Not this plugin. I'll close this. Feel free to reopen if this is not the case

**Comment by VaporeonScripts** [comment]
Wym with og☠️,it's the latest mod version
