### ISSUE TITLE
Unable to use armor and vanilla templates in the smithing table

### ISSUE THREAD

**Issue by YstalX** [Sideways-Sky/Tool-Trims#3]
Unable to use armor and vanilla templates in the smithing table.
1.21.1 Tool-Trims 1.2 Plugin

the vid - https://imgur.com/UO3D1H7

**Comment by AnsonEyre** [comment]
We talked it over on Discord, right? 
https://discord.com/channels/1192180705464168509/1304861424983736380
Anything else?
